In [3]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_digits, load_iris
from sklearn.model_selection import KFold,StratifiedKFold,cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import warnings 
warnings.filterwarnings('ignore')

In [4]:
digits = load_digits()

In [17]:
def get_scores(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

KFolds splits the data into no of splits specified with all the possible combinations

In [9]:
kf = KFold(n_splits=3)

In [10]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


Stratifies KFold will divide the classification category uniformly

In [25]:
skf = StratifiedKFold(n_splits=10)

In [26]:
scores_LR, scores_SVM, scores_RF = [],[],[]

In [28]:
for train_index, test_index in skf.split(digits.data,digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]

    scores_LR.append(get_scores(LogisticRegression(),X_train,X_test,y_train,y_test))
    scores_SVM.append(get_scores(SVC(),X_train,X_test,y_train,y_test))
    scores_RF.append(get_scores(RandomForestClassifier(),X_train,X_test,y_train,y_test))

In [29]:
scores_LR

[0.9055555555555556,
 0.9611111111111111,
 0.8777777777777778,
 0.9277777777777778,
 0.9444444444444444,
 0.9666666666666667,
 0.95,
 0.9385474860335196,
 0.8715083798882681,
 0.9385474860335196]

In [30]:
scores_SVM

[0.9444444444444444,
 0.9888888888888889,
 0.9277777777777778,
 0.9666666666666667,
 0.9833333333333333,
 0.9888888888888889,
 0.9888888888888889,
 0.994413407821229,
 0.9608938547486033,
 0.9553072625698324]

In [31]:
scores_RF

[0.9111111111111111,
 0.9833333333333333,
 0.9333333333333333,
 0.9333333333333333,
 0.9555555555555556,
 0.9611111111111111,
 0.9722222222222222,
 0.9664804469273743,
 0.9273743016759777,
 0.9441340782122905]

Now same above steps can be done through cross_val_score method

In [33]:
cross_val_score(LogisticRegression(),digits.data,digits.target)

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [37]:
np.mean(cross_val_score(LogisticRegression(),digits.data,digits.target))

0.9137650882079852

In [34]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [38]:
np.mean(cross_val_score(SVC(),digits.data,digits.target))

0.9632838130609718

In [35]:
cross_val_score(RandomForestClassifier(),digits.data,digits.target)

array([0.925     , 0.91388889, 0.95264624, 0.97214485, 0.91922006])

In [36]:
np.mean(cross_val_score(RandomForestClassifier(),digits.data,digits.target))

0.9343608789848344